# application.properties
server.port=8082
spring.application.name=events-service

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=events-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.enable-auto-commit: false
spring.kafka.consumer.properties.session.timeout.ms: 30000
spring.kafka.consumer.properties.max.poll.interval.ms: 600000
spring.kafka.consumer.properties.heartbeat.interval.ms: 10000
spring.kafka.properties.retry.backoff.ms: 1000
spring.kafka.properties.reconnect.backoff.max.ms: 10000
spring.kafka.listener.ack-mode: manual
spring.kafka.listener.concurrency: 1


# Logging
logging.level.com.cinemaabyss.events=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
